# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f3841a1b7dec2df8b9092d0273a18f23989fe44a24090ba4970434d760cc525e5a6729051ee4e77d76efb1933b88c12623f29762dcd4c76b84a19ccbc4bcac0

test:
  secret_key_base: dbea3047117b506905d4345ac09170fc61f9deeec302b2a558cf07c3b526a2ae2294ae58463b2b7e70272e721c492f0ecaa20996a2f1e4946ae825728326ffd8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
