# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4da1b48253dbc38a3049595b497fd691378cccf300e7d87bdfdb419c03df26f53a4172f80334e76613190a5752821b5c33d8d52042e76dc75431b1253c40b13d

test:
  secret_key_base: 29c053f10bad18d3f18aa4c0f304b5786c34857797e03ad39e8182c842f0ee865ed1c488530bef8a49463a05ed8963930802d0e2c17473bc08585485e4ccc372

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
